services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-project-backend
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      # Передаем только настройки datasource. Liquibase их подхватит.
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/db_project_dev
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15-alpine
    container_name: my-project-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db_project_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432" # 5432 - может быть занят
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: