# docker-compose up --build
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-project-backend
    restart: unless-stopped
    ports:
      - "12345:12345"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/db_project_dev
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

      - SERVER_PORT=12345

      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
    depends_on:
      - postgres_db
      - redis

  postgres_db:
    image: postgres:15-alpine
    container_name: my-project-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db_project_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432" # 5432 - может быть занят
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: my-project-redis
    restart: unless-stopped
    ports:
      - "6380:6379" 
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data: